### PR TITLE
add disable CORS method

### PR DESCRIPTION
**Pull request by akinazuki**
in the previous version, the default options is enable the CORS options in everywhere, the ```router.options()``` method will never gonna work , because the ```router.handler()``` will preferred to return the corsConfig when the request method is OPTIONS

### CODE REVIEW

**Comment by tsndr** [comment]
Hey, thank you for bringing this bug to my attention.

I've looked at your PR and am very thankful for your help, but I don't want to introduce a new flag, I'd rather want you to specify

```ts
router.cors()
```

to enable CORS headers, they shouldn't be on by default.

Your issue should be fixed with [v2.1.1](https://github.com/tsndr/cloudflare-worker-router/tree/v2.1.1)

**Comment by tsndr** [comment]
We should be good now with [v2.1.1](https://github.com/tsndr/cloudflare-worker-router/tree/v2.1.1), thank you.

**Comment by akinazuki** [comment]
image
you've added corsEnabled  options, but it's protected, and it doesn't have an api to change status

**Comment by tsndr** [comment]
You don't have to worry about that flag, it's only being used internally and is only ever set to `true` if you run `router.cors()`.

Apart from that I've moved some things around in `handle()`, which now allows for OPTIONS routes to work even with CORS enabled:

https://github.com/tsndr/cloudflare-worker-router/blob/d3b86f1dbede8da534a0479b5b054b5d24b12d23/src/index.ts#L412-L428

**Pull request closed without merging**
