### PR TITLE
:package: updated deps

### PR DESCRIPTION
**Pull request by vikiival**
https://blog.cloudflare.com/improving-workers-types/

### CODE REVIEW

**Comment by vikiival** [comment]
I made a [publish on npm for personal purposes](https://www.npmjs.com/package/@vikiival/cloudflare-worker-router)

Going to remove it once it is merged

**Comment by tsndr** [comment]
Thank you for your contribution 🙂

**Comment by tsndr** [comment]
Published with [`v2.3.1`](https://github.com/tsndr/cloudflare-worker-router/tree/v2.3.1)

**Comment by vikiival** [comment]
🫡

Screenshot 2022-11-26 at 12 48 03

**Pull request merged**
